apiVersion: batch/v1
kind: Job
metadata:
  name: create-rpops-cert
  namespace: certbot
spec:
  template:
    spec:
      volumes:
        - name: certbot-pv-storage
          persistentVolumeClaim:
            claimName: certbot-pv-claim
        - name: google-creds
          secret:
            secretName: google-creds
      containers:
      - name: certbot
        image: obmarg/k8s-certbot-google-dns
        imagePullPolicy: Always
        args:
          - certonly
          - -n
          - --agree-tos
          - -m gcoupar@gmail.com
          - --dns-google
          - --dns-google-credentials
          - /etc/google-dns/creds.json
          - -d chatops.rpops.net
          - --deploy-hook
          - cert-deploy.sh
        env:
          - name: CERT_NAMESPACE
            value: <NAMESPACE>
          - name: CERT_SECRET
            value: ingress-cert
          - name: DOMAIN
            value: <A_DOMAIN>
          - name: INGRESS_NAME
            value: <YOUR_INGRESS>
        volumeMounts:
          - mountPath: /etc/letsencrypt
            name: certbot-pv-storage
            subPath: etc
          - mountPath: /var/lib/letsencrypt
            name: certbot-pv-storage
            subPath: var
          - mountPath: /etc/google-dns
            name: google-creds
            readOnly: true
      restartPolicy: OnFailure
      serviceAccountName: certbot
      automountServiceAccountToken: true
