apiVersion: v1
kind: ServiceAccount
metadata:
  name: certbot
  namespace: certbot
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot-binding
  namespace: deployr # This only grants permissions within the "deployr" namespace.
subjects:
- kind: ServiceAccount
  name: certbot
  namespace: certbot
roleRef:
  kind: ClusterRole
  name: certbot
  apiGroup: rbac.authorization.k8s.io
